# Generated by Django 5.2 on 2025-04-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=150)),
                ("source", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "product_type",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=300)),
                ("basic_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="product.producttype"),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
