# Generated by Django 5.2 on 2025-04-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("status_machine", "0002_alter_orderstatus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("signed", models.BooleanField(default=False)),
                ("start_date", models.DateField(null=True, verbose_name="Order start date")),
                ("snapshot", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        default=1, on_delete=django.db.models.deletion.DO_NOTHING, to="status_machine.orderstatus"
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orderlines", to="order.order"
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="product.product")),
            ],
            options={
                "db_table": "order_line",
            },
        ),
    ]
