# Generated by Django 5.2 on 2025-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="snapshot",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
