# Generated by Django 5.2 on 2025-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_to_customer',
            field=models.BooleanField(default=False),
        ),
    ]
