# Generated by Django 5.2 on 2025-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.IntegerField(verbose_name="Status code")),
                ("description", models.CharField(verbose_name="description")),
            ],
            options={
                "db_table": "order_status",
            },
        ),
    ]
