# Generated by Django 5.2 on 2025-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("status_machine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderstatus",
            options={"ordering": ["code"], "verbose_name_plural": "order statuses"},
        ),
    ]
